### ISSUE TITLE
vaguely unsatisfying finish [minor]

### ISSUE THREAD

**Issue by joeyh** [yamadapc/haskell-ascii-progress#13]
As a progress bar conissour, I live for that moment when it hits 100%. That's the psycholocial payoff for the whole progress bar experience.

So, the current display is a trifle unsatisfying. The progress bar gets to `[==========  ]`19/20 and then goes away, incomplete. Might not look like much to some, but to us progress bar conissour's, it might as well be `[=====      ] 19/20`

(As a progress bar implementor, I know that they often lie in subtle ways, and a subtle lie is probably the best way to approach this. Make the bar display `[============]` 19/20
filling in that crucial last step of the progress display one block ahead of actually finshing.)

**Comment by yamadapc** [comment]
By default progress-bars now output the full completed bar. For doing more, use `pgFuture`. It fulfils after `pgOnCompletion` is outputted.

**Comment by yamadapc** [comment]
The region is not closed. Are there problems with that?
