### ISSUE TITLE
simplify interface via concurrent-output

### ISSUE THREAD

**Issue by joeyh** [yamadapc/haskell-ascii-progress#16]
My new library http://hackage.haskell.org/package/concurrent-output/ provides a kind of tiling region manager for the console. It's full-featured, robust, and has highly efficient output.

So, I suggest removing the overlapping functionality for screen drawing from ascii-progress, leaving only the core progress bar calculation and rendering functionality.
Something like:

    newProgressBar :: Options -> (Text -> IO ()) -> IO ProgressBar

    tick :: ProgressBar -> IO ProgressBar

Using this from concurrent-output would look something like:

    import System.Console.Regions
    main = displayConsoleRegions $
        async $ withConsoleRegion Linear $ \r -> do
            p1 <- newProgressBar def (setConsoleRegion r)
            forever $
                threadDelay 100000
                tick p1
        -- more async calls for other progress bars to display at the same time

Taking this approach should close #8, #5, #7, #9, #11, #12, which are all addressed by concurrent-output.

**Comment by yamadapc** [comment]
I'm currently on a conference, had a quick look at your module. Nice!
I'll try doing this today or tomorrow. Just so I understand, how does this solve #5 (being aware of the terminal width)? I saw you have `terminal-size` but couldn't find something on the API about it.

**Comment by joeyh** [comment]
Pedro Tacla Yamada wrote:
> I'm currently on a conference, had a quick look at your module. Nice!
> I'll try doing this today or tomorrow. Just so I understand, how does this
> solve #5 (being aware of the terminal width)? I saw you have terminal-size but
> couldn't find something on the API about it.

System.Console.Regions keeps track of the terminal width, including
noticing resizes, and so knows if a region's content is longer than will
fit onto a line. By default it then splits the region to display on
multiple lines.

There's also the ability (as of yesterday) to make a region's content be a STM
action which can then call consoleWidth, which will always return the current
width.

So for example, here's a region that displays 0..9 repeating all
the way across one line of the console:

  rulerRegion :: IO ConsoleRegion
  rulerRegion = do
        r <- openConsoleRegion Linear
        setConsoleRegion r $ do
                width <- consoleWidth
                return $ T.pack $ take width nums
        return r
    where
        nums = cycle $ concatMap show [0..9]
  
-- 
see shy jo

**Comment by yamadapc** [comment]
Okay; what you've done is really cool. Thanks a lot for it, it's really useful. I'm going to take the time this afternoon to use your library.

**Comment by yamadapc** [comment]
Okay; I've mostly did porting, I'd like some other minor improvements since this will be a breaking release.

I need to go through your code a little better.

I added an example which shows a slight problem with #8 though. I need to expose passing the region in rather than creating it too. Anyway, this is the example on the branch I just pushed which has weird output:
```haskell
import           Control.Concurrent           (forkIO, threadDelay)
import           Control.Concurrent.Async     (wait)
import           Control.Monad                (forM, unless)
import           System.Console.AsciiProgress
import           System.Random                (randomRIO)

main :: IO ()
main = displayConsoleRegions $ do
    fs <- forM ([0..100] :: [Int]) $ \i -> do
        pg <- newProgressBar def { pgWidth = 100
                              , pgOnCompletion = Just $ "pg " ++ show i ++ " is Done!"
                              }
        speed <- (* 1000) <$> randomRIO (3, 10)
        _ <- forkIO $ loop pg speed
        return $ pgFuture pg
    waitAll fs
  where
    waitAll [] = return ()
    waitAll (f:fs) = wait f >> waitAll fs
    loop pg ts = do
        b <- isComplete pg
        unless b $ do
            threadDelay ts
            tick pg
            loop pg ts
```

**Comment by mitchellwrosen** [comment]
@joeyh Huh, I tried running the demos included with `concurrent-output` and they all came out garbled. Simple usage of `ascii-progress` (the version on Hackage), however, seem to work okay.

**Comment by joeyh** [comment]
Mitchell Rosen wrote:
> @joeyh Huh, I tried running the demos included with concurrent-output and they
> all came out garbled. Simple usage of ascii-progress (the version on Hackage),
> however, seem to work okay.

I heard there might be an issue in some terminal on OSX. I'm not able to
test that. concurrent-output should work on any terminal that supports
ANSI cursor movement codes (and also on Windows).

-- 
see shy jo

**Comment by joeyh** [comment]
Pedro Tacla Yamada wrote:
> I added an example which shows a slight problem with #8 though. I need to
> expose passing the region in rather than creating it too. Anyway, this is the
> example on the branch I just pushed which has weird output:

The output I see from CrazyMultiExample.hs seems to be what I'd expect,
testing on Linux in an XFCE terminal:

* Displays 100 concurrent progress bars.
* Since I normally have less than 100 lines in my terminal, it only
  displayed the bottom-most N 
* Progress bars never overwrote others etc, and there were no display
  gliches. (There was some screen flicker due to so many things going on
  at once.)
* At the end all 100 "pg N is Done" were left on screen.

-- 
see shy jo

**Comment by mitchellwrosen** [comment]
@joeyh Huh, that's a bummer. Here's an example of the behavior I see:

![x](http://i.imgur.com/Y51oRvP.gif)

**Comment by joeyh** [comment]
Thanks for the example. Looks like it's failing to move the cursor up
to the previously output lines in order to change them.

The eqivilant code without concurrent-progress or threads is:

	import System.Console.ANSI
	import Control.Concurrent

	main = do
	        putStrLn "hi"
	        cursorUp 1
	        putStrLn "hello"
	        putStrLn "hi   "
	        threadDelay 1000000
	        cursorUp 1
	        putStrLn "bye"
	        cursorDown 1

I guess this will similarly display 4 lines on your console, rather than
the 2 it should, and if so that proves your console doesn't support
ANSI cursor movement sequences.

-- 
see shy jo

**Comment by joeyh** [comment]
Actually, could you try my sample program using cursorUp as given, and
then try replacing that with cursorUpLine?

concurrent-output currently uses cursorUpLine; perhaps
it should be using cursorUp.

I had not noticed both of those existed as different things, and they
may not do the same thing on all terminals; Wikipedia notes that
cursorUpLine was not in DOS's ansi.sys for example. Perhaps OSX is a lot
like DOS. ;)

-- 
see shy jo

**Comment by joeyh** [comment]
I've pushed a cursorlines to concurrent-output's git repository which
avoids using cursorUpLine. Testing welcome..

-- 
see shy jo

**Comment by mitchellwrosen** [comment]
@joeyh The above example looks correct with `cursorUp` and incorrect with `cursorUpLine`. Good work! However, I don't see any updates to the git repo so I can't test the larger examples.

**Comment by joeyh** [comment]
Great; that is probably fixed by concurrent-output 1.6.1.

-- 
see shy jo

**Comment by mitchellwrosen** [comment]
@joeyh Where can I submit bug reports to you in the future? - This GH issue certainly isn't right :)

**Comment by yamadapc** [comment]
What I get from `crazy-multi-example`:

### iTerm2
![iterm2](https://cloud.githubusercontent.com/assets/3923654/11036847/e9f32828-86e1-11e5-9bac-7defd2ae4a7d.gif)

### tmux
![tmux](https://cloud.githubusercontent.com/assets/3923654/11036852/f2a34a66-86e1-11e5-801f-8a5ef5062d2b.gif)

### Terminal
![terminal](https://cloud.githubusercontent.com/assets/3923654/11036860/fd5983da-86e1-11e5-811c-53e3d5b90891.gif)

**Comment by joeyh** [comment]
Looks right except for the iterm one doesn't it?

Seems like iterm may also be ignoring the ANSI codes to move the cursor
back to column 0, or perhaps you're using the old concurrent-output and
the new one fixes it, I'm not sure.

-- 
see shy jo

**Comment by yamadapc** [comment]
Mm... I'm using concurrent-output from HEAD actually, because 1.6 wasn't published yet when I started. I've updated the example to illustrate what I was expecting vs what I got:

![terminal](https://cloud.githubusercontent.com/assets/3923654/11038083/5caea4ea-86e8-11e5-8059-40c97bc0e43f.gif)

Everything looks ok, except for the first line and the `finishConsoleRegion` messages when old regions are overflowing vertically from the screen.

**Comment by yamadapc** [comment]
I get similar output from gnome-terminal

**Comment by joeyh** [comment]
What's going on with the first line is that since there are too many regions to fit on screen, it moves all the way up to line 1 in order to display all regions above. But, I think that was fixed already in current versions of concurrent-output, particularly by commit 86b77ad8307da25908559e776a847fd3b2c036ab, which makes it avoid drawing regions that are offscreen.

The flicker from the finishConsoleRegion messages is because it has to redraw the entire screen in this situation when one occurs. I could use ansi codes to scroll the screen down, and put the message in the added space, but those ansi codes are not portable, and I'm sure would fail to work on OSX. I could avoid displaying the finishConsoleRegion message when it won't fit on the screen, and so avoid the flicker, but then these messages would not be in the scrollback buffer. This redisplay is only obvious when there are such a large number of region on the screen, so I think it's a reasonable tradeoff (and if you don't want it, just avoid using finishConsoleRegion).

**Comment by mitchellwrosen** [comment]
@joeyh I think I've discovered a bug:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Control.Concurrent
import Control.Concurrent.STM.TVar
import Control.Monad.STM
import Data.Text (pack)
import System.Console.Regions

main = displayConsoleRegions $ do
    var <- newTVarIO 0
    withConsoleRegion Linear $ \parent ->
     withConsoleRegion (InLine parent) $ \child -> do
        setConsoleRegion child (pack . show <$> readTVar var)
        countTo 10 var

countTo :: Int -> TVar Int -> IO ()
countTo n var = go 0
  where
    go m | m == n = pure ()
         | otherwise = do
             atomically (writeTVar var m)
             threadDelay 100000
             go (m+1)
```

When I run this I see no output. Am I misunderstanding `InLine` here? BTW - this example *does* work if reworked slightly, so `setConsoleRegion` is called multiple times with a `Text` rather than once with an `STM Text`, i.e.

```haskell
main = displayConsoleRegions $ do
    withConsoleRegion Linear $ \parent ->
     withConsoleRegion (InLine parent) $ \child -> do
        countTo 10 child

countTo :: Int -> ConsoleRegion -> IO ()
countTo n region = go 0
  where
    go m | m == n = pure ()
         | otherwise = do
             setConsoleRegion region (show m)
             threadDelay 100000
             go (m+1)
```

**Comment by joeyh** [comment]
Mitchell Rosen wrote:
> @joeyh I think I've discovered a bug:

A bug indeed. (Let's send any other ones to my email directly unless I
end up putting up some kind of bug tracker for concurrent-output.)

This is one of those nice bugs that can be fixed by simplifying the
code! Fixed in 1.7.0.

-- 
see shy jo

**Comment by mitchellwrosen** [comment]
That was fast! Thanks.

**Comment by yamadapc** [comment]
Pushed as `0.3.0.0`. Nice!

**Comment by joeyh** [comment]
Pedro Tacla Yamada wrote:
> Pushed as 0.3.0.0. Nice!

Glad it seems to be working out. Of course, I welcome suggestions for
improvements to concurrent-output, especially if the API could be
improved in some way.

Hey, your big example in Console.AsciiProgress forgets to call
displayConsoleRegions!

-- 
see shy jo
