### ISSUE TITLE
Use MonadIO rather than IO

### ISSUE THREAD

**Issue by expipiplus1** [yamadapc/haskell-ascii-progress#18]
It would be handy to be able to call the functions in this package from any `IO` featured monad without using `liftIO`

**Comment by yamadapc** [comment]
I feel like this isn't really a concern here. I'd rather people be able to use it very easily.

What you can do, which should be fairly straightforward is:
```haskell
import Control.Concurrent
import Control.Monad.IO.Class
import Control.Monad.Trans.Reader
import System.Console.AsciiProgress

type ProgressM = ReaderT ProgressBar IO

runProgress :: ProgressM a -> ProgressBar -> IO a
runProgress = runReaderT

tickT :: ProgressM ()
tickT = do
    pg <- ask
    liftIO (tick pg)

main :: IO ()
main = displayConsoleRegions $ do
  pg <- newProgressBar def
  flip runProgress pg $ do
    tickT
    liftIO $ threadDelay (1000 * 1000)
    tickT
    liftIO $ threadDelay (1000 * 1000)
    tickT
    liftIO $ threadDelay (1000 * 1000)
    tickT
    liftIO $ threadDelay (1000 * 1000)
    tickT
```

Then just build your own monad transformers stack. I'm not super into adding that to the default interface. But would accept a PR with `System.Console.AsciiProgress.Trans`.

In the end of the day, as far as I can tell, things will have to use `liftIO . tick`, no?

**Comment by yamadapc** [comment]
Closing, feel free to submit a PR with a `ReaderT` interface
