### ISSUE TITLE
unbounded pgTotal

### ISSUE THREAD

**Issue by joeyh** [yamadapc/haskell-ascii-progress#2]
pgTotal is an Int. If used to indicate size in bytes, that limits the size to 8388608 terabytes on 64 bit (probably enough for now), and only 2 gigabytes on i386. The latter is a problem.

Of course, pgTotal could be used to indicate size in kilobytes or some other scaling factor, but this will complicate the program using this library. It will need to do math correctly, which the API currently nicely avoids. ;) Also, picking too large a scaling factor will lead to blocky updates, especially if the download is going slowly.

For these reasons, I think pgTotal should be changed to an Integer, unless there's some performance reaason not to.

**Comment by yamadapc** [comment]
This is an easy fix. I've already made the changes on my local machine, leaving `tickN` as:
```haskell
tickN :: Integral a => ProgressBar a -> IO ()
```

Which shouldn't be a breaking change, though we might have to introduce breaking changes for some of these issues you've just opened.

**Comment by yamadapc** [comment]
Forcing people to use explicit signatures on literals is less than ideal though.
