### ISSUE TITLE
Custom rendering

### ISSUE THREAD

**Issue by joeyh** [yamadapc/haskell-ascii-progress#3]
If I'm downloading a file, I don't want to display 322112/2929933 to the user but more something like "32MB".

I don't know how to fit Stats -> String into the pgFormat interface, but my wish is a way to do that. (IIRC there were some ideas for a better format interface on the reddit thread.)

Alternatively, it could contain a SI data units format string. I have a nice little library in git-annex that can format them, that could be broken out to hackage. 

But, I feel embedding a particular data units display in the progress bar library is the wrong choice. For example, in the case of git-annex I want it to consistently use the same style for displaying data sizes throughout the program, including in progress bars. If the progress bar library does its own formatting of them, I don't really have the control I want.

**Comment by joeyh** [comment]
This is low priority for git-annex, it can just use ":percent of 292MB" for now..

**Comment by yamadapc** [comment]
This is an interesting issue. I wonder if it'd be possible to use the type system (after changing the format string to be more Haskell-like, as proposed in the Reddit thread) to solve it.

**Comment by joeyh** [comment]
For a simple solution, I'd be fine with just a String -> String function
that could be optionally provided to alter the progress bar after
ascii-progress has generated it.

-- 
see shy jo

**Comment by yamadapc** [comment]
Yeah... But I'm not sure how that'd fix the problem though. You'd have to reimplement the printing function on your application, if you wanted to keep the bars with the same length, consistently. Given I'm exposing `System.Console.AsciiProgress.Internal`, maybe letting the user provide `getProgressStr` would be the simple solution.

**Comment by yamadapc** [comment]
I think using the [formatting](https://github.com/chrisdone/formatting) package and letting people provide their own formatters will fix the problem. I'll first adjust the code to use it, then I'll try to let users provide formatters in a nice API.

**Comment by yamadapc** [comment]
I've implemented a preliminary version of the changes to use `formatting`. I'm not super happy about how format specs need to look (lots of `%` and `<>`, isn't as friendly as I'd like it to be) and there're some clear "issues" related to `Text/String` conversion, because I'm lazy. I'm going to keep the `String` interface side-by-side with this one.

Next stop writing formatters or examples for mega/kilo/byte units. This isn't actually needed that much though.

Now `pgFormat` has type:
```
pgFormat :: Format Text Stats
```
So users can define whatever formatters you want that take the `Stats` type. You can also combine existing formatters like `eta` or `current` with something that'd format the units as you'd like.

Next stop `STM`... :smiley:

**Comment by yamadapc** [comment]
The `download-example` on the `dev` branch now shows off this feature :)

**Comment by joeyh** [comment]
I've checked this branch out now. 

One thing I noticed is that it increases the size of a executable using ascii-progress significantly from the old version. After stripping:

  -rwxr-xr-x 1 joey joey 1000K Apr 11 10:19 MultiExample.old*
  -rwxr-xr-x 1 joey joey  2.4M Apr 11 10:19 MultiExample*

I suspect that a lot of this bloat comes from double-conversion, which is a 6 mb source package including an enormous C++ library! Although it seems it boils down to a 117k .a file, so an additional megabyte is coming from somewhere else.

This seems suboptimal for the benefits to me. I already have a 50 mb git-annex executable;
bloating it by this much more just for progress bars feels weird. If I had a smaller program, maybe a 3 or 4 mb executable, that might mean a 50% size increase for progress bars.

(BTW, the docs for double-conversion say it's 30x faster than `show`. Which would be great if emitting large numeric data sets, but for a progress bar, that is probably going to update less than 10x per second, is serious overkill.)

**Comment by yamadapc** [comment]
Oh... Man... That's so sad. I thought ` formatting` was a reasonably standard package.

**Comment by joeyh** [comment]
Maybe allowing the user to provide getProgressTxt is the right low-level API? The returned Text could be truncated to the specified width before ascii-progress displays it.

There could then be an ascii-progress-formatting that provides the nice formatting based interface on top of it.

Hrm, I guess you'd also need to expose some Stats -> Txt functions to do things like draw the [===] progress element, etc.

**Comment by yamadapc** [comment]
Yeah... That's about what I was thinking, it's just going to make things a lot more complicated on this package. I'd rather have `ascii-progress-minimal` with a low-level interface and keep this one pretty. We'll see, I'm looking over the rendering problems first.
