### ISSUE TITLE
please support ghc 7.6.3

### ISSUE THREAD

**Issue by joeyh** [yamadapc/haskell-ascii-progress#4]
I am considering using this library in git-annex. However, ascii-progress currently does not support the version of ghc used in Debian testing. Since git-annex needs to work with not only the next debian release, but the current one, and ideally even the one before that, this means I can currently hope to use ascii-progress somethime in 2021. :-/

I took a look at the cabal dependencies, and it seems that the examples use http conduit and maybe other stuff at problimatic versions for the old ghc. But the library itself actually does not, and in fact I have it installed here using ghc 7.6.3, after disabling the examples and making one other change.

FWIW, I have not looked at the examples, but I've found it not very hard to write code that works with both current and past versions of http-conduit. IIRC the new version uses a type "Request -> Request" while the old version uses "forall m. Request m -> Request m", and all I had to do was ifdef code to use the right type signature. (See Utility/Url.hs in git-annex for an example.)

The other change I mentioned is that tryReadMVar is not available. I hacked around it using tryTakeMVar and tryPutMVar. I don't think that can behave the same, in the case where the MVar is read, and then something else comes in and fills it before the value is stored back.  My hack was good enough to see the library in action anyway. 

    tryReadMVar ::  MVar a -> IO (Maybe a)
    tryReadMVar mv = go =<< tryTakeMVar mv
      where
        go Nothing = return Nothing
        go (Just v) = do
                _ <- tryPutMVar mv v -- this hack may fail!
                return (Just v)

Rather than this hack, you could use STM. There is a tryReadTMVar in STM that works fine with old ghc.

**Comment by joeyh** [comment]
Note that git-annex actually supports back to ghc 7.4.1.

**Comment by yamadapc** [comment]
Yeah... The only reason I didn't use `STM` rather than plain `Control.Concurrent` is it isn't in base. I guess it isn't a problem to include it. And it'd make all the code around shared memory a lot less fragile.

**Comment by yamadapc** [comment]
It seems to me STM would work on 7.4.1 too.

**Comment by joeyh** [comment]
Pedro Tacla Yamada wrote:
> It seems to me STM would work on 7.4.1 too.

Yes, STM is fine on 7.4.1. 

And yeah, it makes concurrent programming a lot nicer often. Of course
it can also make it slower sometimes.

-- 
see shy jo

**Comment by joeyh** [comment]
Also, the versioned bounds on time can be relaxed to time >= 1.4.0.1 which is what comes bundled with ghc 7.6.3.

**Comment by joeyh** [comment]
Checked this out, and the text dependency can also be relaxed, at least to 0.11.3

With that change, and after deleting the cabal file's stanzas for executables and test-suite (due to it needing newer versions of http-conduit than it's necessarily easy to install), it cabal installs on debian unstable.

**Comment by yamadapc** [comment]
Fixed in `0.3.2.0`:
https://travis-ci.org/yamadapc/haskell-ascii-progress/jobs/90404039
