### ISSUE TITLE
better support for unknown size

### ISSUE THREAD

**Issue by joeyh** [yamadapc/haskell-ascii-progress#6]
In git-annex, it's possible (though unusual) for the sizes of some files being downloaded to not be known in advance. 

The best that can be done with the ascii-progress API in this situation is to never tick that progress bar until the download is complete, and then tick it forward to 100%. But of course, that's a non-informative progress bar of the worst sort..

It would be nice to have some way to indicate activity even if the progress cannot be updated. So rather than a progress bar, this would be a progress spinner, that spins when
there's some activity. 

I'm thinking something like a .oOo.oOo. bubbler ascii art and a "21MB downloaded" display. 

The bubbler would be nice to have in ascii-progress. The "21 MB downloaded" is custom rendering, as I requested in https://github.com/yamadapc/haskell-ascii-progress/issues/3

**Comment by yamadapc** [comment]
Have you ever seen TJ's [go-spin](https://github.com/tj/go-spin) package? I have a partial implementation of that, it's really simple to do in haskell too, but it doesn't demonstrate any progress. My [haskell-drawille](https://github.com/yamadapc/haskell-drawille) package can also be used to demonstrate downloading blocks in a fancy way.

**Comment by yamadapc** [comment]
Oh... I had completely forgotten about this. I have another terminal interface related project that exposed exactly this: https://github.com/yamadapc/haskell-questioner/blob/master/src/System/Console/Questioner/ProgressIndicators.hs
