### ISSUE TITLE
registerLn racy

### ISSUE THREAD

**Issue by joeyh** [yamadapc/haskell-ascii-progress#9]
If I putStrLn and then registerLn, there is a window where the progress bar may update and, not knowing about the line yet, write over the string I displayed.

Conversely, if I registerLn and then putStrLn, the progress bar update may happen before the putStrLn, so the cursor may be in a different position (including half-way across the screen's width) when the text is output.

I have not seen either of these in the wild, but I think this analysis makes sense?

Seems to me the only safe interface is to provide some way to prevent progress bar display
while the putStrLn is happening. I suggest: showLn :: String -> IO ()

**Comment by yamadapc** [comment]
Yeah... I was thinking that exposing something like `pgPutStrLn :: String -> IO ()` would be a better solution than `registerLn`. I've built a small program which should prove this is wrong, though. I'm not sure, I'll have to test.

**Comment by joeyh** [comment]
One thing that occured to me is that I will sometimes want to output
stderr, so the interface should allow that, not only stdout.

(Someone might be running the program with the progress output sent to
/dev/null, and still want to see errors.)

-- 
see shy jo

**Comment by yamadapc** [comment]
I guess `pgHPutStrLn :: Handle -> String -> IO ()` too then :smile:

**Comment by yamadapc** [comment]
Also if I manage to fix #7, there'd be functions for printing before and after the progress bars are displayed.
